### ISSUE TITLE
Unread background color stand out in dark theme.

### ISSUE THREAD

**Issue by nyoronjp** [support-project/knowledge#863]
未読の背景色がダークテーマだと目立つ。

Knowledge v1.11.0 pre1

![darktheme](https://user-images.githubusercontent.com/3918654/30648048-0f8659b8-9e58-11e7-9fba-c7c823d66d30.png)

knowledge-list.css
```css
.unread {
    background-color: #e5fcff;
}
```
