### ISSUE TITLE
Horizontal scrollbar appears when Grid options "Small devices "

### ISSUE THREAD

**Issue by nyoronjp** [support-project/knowledge#868]
投稿画面で横スクロールバーが出現する。  

`.col-sm-4`の横幅＋右余白がタグ入力欄の横幅(300px)より小さい時。

```css
.bootstrap-tagsinput input {
    min-width: 300px;
}
```

![horizontal scrollbar](https://user-images.githubusercontent.com/3918654/30782859-7c41db9e-a174-11e7-9566-3f63edbd155f.png)

こちらではChromeのwindow sizeを768px～942px(縦スクロールバー込?)で起こりました。
